-- Create products table
create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price decimal(10,2) not null,
  image text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.products enable row level security;

-- Create policy for public read access
create policy "Products are viewable by everyone" on public.products
  for select using (true);

-- Create policy for authenticated users to insert/update/delete
create policy "Authenticated users can manage products" on public.products
  for all using (auth.role() = 'authenticated');